-- Vokabel Lab
-- Base schema for Supabase / PostgreSQL
-- Run this file in the Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Optional cleanup for repeated local testing in a fresh project.
-- Uncomment only if you want to recreate everything.
-- drop table if exists public.session_answers cascade;
-- drop table if exists public.study_sessions cascade;
-- drop table if exists public.user_progress cascade;
-- drop table if exists public.profiles cascade;
-- drop table if exists public.vocabulario cascade;

create table if not exists public.vocabulario (
  id bigint generated by default as identity primary key,
  de text not null,
  es text not null,
  artikel text,
  thema integer not null check (thema > 0),
  type text not null,
  source text default 'manual_import',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_vocabulario_entry on public.vocabulario (de, es, thema, type);
create index if not exists idx_vocabulario_thema on public.vocabulario (thema);
create index if not exists idx_vocabulario_type on public.vocabulario (type);
create index if not exists idx_vocabulario_thema_type on public.vocabulario (thema, type);

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  preferred_lang text default 'es',
  level_label text,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  vocabulario_id bigint not null references public.vocabulario (id) on delete cascade,
  status text not null default 'new' check (status in ('new', 'learning', 'review', 'mastered')),
  correct_count integer not null default 0 check (correct_count >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  streak integer not null default 0 check (streak >= 0),
  last_mode text check (last_mode in ('write', 'cards', 'mc')),
  last_seen_at timestamptz,
  next_review_at timestamptz,
  mastered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_progress_unique unique (user_id, vocabulario_id)
);

create index if not exists idx_user_progress_user on public.user_progress (user_id);
create index if not exists idx_user_progress_review on public.user_progress (user_id, next_review_at);
create index if not exists idx_user_progress_status on public.user_progress (user_id, status);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  mode text not null check (mode in ('write', 'cards', 'mc', 'mixed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  total_words integer not null default 0 check (total_words >= 0),
  correct_answers integer not null default 0 check (correct_answers >= 0),
  wrong_answers integer not null default 0 check (wrong_answers >= 0),
  selected_themas integer[] not null default '{}',
  selected_types text[] not null default '{}',
  notes jsonb not null default '{}'::jsonb
);

create index if not exists idx_study_sessions_user_started on public.study_sessions (user_id, started_at desc);

create table if not exists public.session_answers (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.study_sessions (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  vocabulario_id bigint not null references public.vocabulario (id) on delete cascade,
  mode text not null check (mode in ('write', 'cards', 'mc')),
  is_correct boolean not null,
  user_answer text,
  correct_answer text,
  answered_at timestamptz not null default now()
);

create index if not exists idx_session_answers_session on public.session_answers (session_id);
create index if not exists idx_session_answers_user_vocab on public.session_answers (user_id, vocabulario_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vocabulario_updated_at on public.vocabulario;
create trigger set_vocabulario_updated_at
before update on public.vocabulario
for each row
execute function public.set_updated_at();

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists set_user_progress_updated_at on public.user_progress;
create trigger set_user_progress_updated_at
before update on public.user_progress
for each row
execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

alter table public.vocabulario enable row level security;
alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.study_sessions enable row level security;
alter table public.session_answers enable row level security;

drop policy if exists "Public can read active vocabulario" on public.vocabulario;
create policy "Public can read active vocabulario"
on public.vocabulario
for select
using (is_active = true);

drop policy if exists "Admins can manage vocabulario" on public.vocabulario;
create policy "Admins can manage vocabulario"
on public.vocabulario
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists "Users manage own progress" on public.user_progress;
create policy "Users manage own progress"
on public.user_progress
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own sessions" on public.study_sessions;
create policy "Users manage own sessions"
on public.study_sessions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users manage own answers" on public.session_answers;
create policy "Users manage own answers"
on public.session_answers
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Suggested thema reference for the UI:
-- 1  Zeit & Natur
-- 2  Essen & Einkaufen
-- 3  Familie & Alltag
-- 4  Hobbys & Freizeit
-- 5  Wohnen
-- 6  Kleidung & Haushalt
-- 7  Stadt & Kultur
-- 8  Im Restaurant
-- ...
-- 29 Politik & Gesellschaft

-- Import note:
-- Your existing vocabulario.sql is MySQL syntax.
-- Easiest path:
-- 1. Run this schema first.
-- 2. Convert the INSERT rows to PostgreSQL-compatible inserts.
-- 3. Import only into public.vocabulario (de, es, thema, type, artikel if available).
