insert into public.vocabulario (de, es, thema, type) values
('die Landschaft', 'paisaje', 1, 'Nomen'),
('die Tageszeiten', 'las partes del día', 1, 'Nomen'),
('am Morgen', 'por la mañana', 1, 'Ausdruck'),
('vormittags', 'por la mañana (antes de mediodía)', 1, 'Adjektiv/Adverb'),
('der Mittag', 'mediodía', 1, 'Nomen'),
('am Abend / nachts', 'por la noche', 1, 'Ausdruck'),
('der Wochentag', 'día de la semana', 1, 'Nomen'),
('der Donnerstag', 'jueves', 1, 'Nomen'),
('die Jahreszeit', 'estación del año', 1, 'Nomen'),
('der Frühling', 'primavera', 1, 'Nomen'),
('das Datum', 'fecha', 1, 'Nomen'),
('die Zeit', 'tiempo', 1, 'Nomen'),
('die Uhrzeit / die Stunde', 'hora', 1, 'Nomen'),
('der Termin', 'cita', 1, 'Nomen'),
('der Kalender', 'agenda', 1, 'Nomen'),
('der Tag', 'día', 1, 'Nomen'),
('der Feiertag', 'día festivo', 1, 'Nomen'),
('die Woche', 'semana', 1, 'Nomen'),
('das Wochenende', 'fin de semana', 1, 'Nomen'),
('Anfang Mai', 'a principios de mayo', 1, 'Nomen'),
('heute', 'hoy', 1, 'Adjektiv/Adverb'),
('der Ausflug', 'excursión', 1, 'Nomen'),
('nach Hause gehen / zurückgehen', 'ir (volver) a casa', 1, 'Verb'),
('das Restaurant', 'restaurante', 1, 'Nomen'),
('der Park', 'parque', 1, 'Nomen'),
('die Natur', 'naturaleza', 1, 'Nomen'),
('das Wetter', 'tiempo (meteorológico)', 1, 'Nomen'),
('der Regen', 'lluvia', 1, 'Nomen'),
('die Sonne', 'sol', 1, 'Nomen'),
('der Grad', 'grado', 1, 'Nomen'),
('die Chefin', 'jefa', 1, 'Nomen'),
('der Direktor', 'director', 1, 'Nomen'),
('der Kollege / die Kollegin', 'colega / compañera', 1, 'Nomen'),
('der Anfang', 'comienzo', 1, 'Nomen'),
('der Freund', 'amigo', 1, 'Nomen'),
('die Karte', 'tarjeta', 1, 'Nomen'),
('die Mutter', 'madre', 1, 'Nomen'),
('der Vater', 'padre', 1, 'Nomen'),
('das Plakat', 'cartel / pancarta', 1, 'Nomen'),
('die SMS', 'SMS', 1, 'Nomen'),
('das Tier', 'animal', 1, 'Nomen'),
('der Zettel', 'papel (de nota)', 1, 'Nomen'),
('anfangen / beginnen', 'empezar', 1, 'Verb'),
('besuchen', 'visitar (también asistir a un curso)', 1, 'Verb'),
('finden', 'encontrar', 1, 'Verb'),
('geben', 'dar', 1, 'Verb'),
('hoffentlich', 'ojalá', 1, 'Adjektiv/Adverb'),
('mit', 'con', 1, 'Adjektiv/Adverb'),
('von … bis', 'desde… hasta', 1, 'Ausdruck'),
('wann?', '¿Cuándo?', 1, 'Adjektiv/Adverb'),
('das Obst', 'fruta', 2, 'Nomen'),
('die Orange', 'naranja', 2, 'Nomen'),
('der Salat', 'ensalada / lechuga', 2, 'Nomen'),
('die Zwiebel', 'cebolla', 2, 'Nomen'),
('die Beilage', 'guarnición', 2, 'Nomen'),
('die Kartoffel', 'patata', 2, 'Nomen'),
('der Reis', 'arroz', 2, 'Nomen'),
('der Käse', 'queso', 2, 'Nomen'),
('der Emmentaler', 'queso emmenthal', 2, 'Nomen'),
('die Milch', 'leche', 2, 'Nomen'),
('das Brot', 'pan', 2, 'Nomen'),
('das Brötchen', 'panecillo', 2, 'Nomen'),
('der Kuchen', 'pastel / bizcocho', 2, 'Nomen'),
('das Fleisch', 'carne', 2, 'Nomen'),
('die Wurst', 'salchicha / embutido', 2, 'Nomen'),
('das Salz', 'sal', 2, 'Nomen'),
('der Zucker', 'azúcar', 2, 'Nomen'),
('das Eis', 'helado', 2, 'Nomen'),
('das Getränk', 'bebida', 2, 'Nomen'),
('der Orangensaft', 'zumo de naranja', 2, 'Nomen'),
('das Wasser', 'agua', 2, 'Nomen'),
('einkaufen gehen', 'ir de compras', 2, 'Verb'),
('der Einkauf', 'la compra', 2, 'Nomen'),
('die Verkäuferin', 'vendedora', 2, 'Nomen'),
('der Supermarkt', 'supermercado', 2, 'Nomen'),
('das Angebot', 'oferta', 2, 'Nomen'),
('der Preis', 'precio', 2, 'Nomen'),
('die Dose', 'lata', 2, 'Nomen'),
('die Flasche', 'botella', 2, 'Nomen'),
('die Packung', 'envase / paquete', 2, 'Nomen'),
('die Tafel', 'tableta', 2, 'Nomen'),
('die Tüte', 'bolsa', 2, 'Nomen'),
('die Eltern', 'padres', 3, 'Nomen'),
('der Sohn', 'hijo', 3, 'Nomen'),
('die Tante', 'tía', 3, 'Nomen'),
('die Frau', 'mujer / esposa', 3, 'Nomen'),
('der Arzt', 'médico', 3, 'Nomen'),
('die Informatik', 'informática', 3, 'Nomen'),
('kochen', 'cocinar / hervir', 3, 'Verb'),
('aufwachen', 'despertar', 3, 'Verb'),
('das Problem', 'problema', 3, 'Nomen'),
('erzählen', 'contar', 3, 'Verb'),
('vergleichen', 'comparar', 3, 'Verb'),
('anders / verschieden', 'diferente', 3, 'Adjektiv/Adverb'),
('möglich', 'posible', 3, 'Adjektiv/Adverb'),
('nicht mehr', 'ya no', 3, 'Adjektiv/Adverb'),
('alles', 'todo', 3, 'Adjektiv/Adverb'),
('wenig', 'poco', 3, 'Adjektiv/Adverb'),
('viel', 'mucho', 3, 'Adjektiv/Adverb'),
('okay', '¡vale!', 3, 'Adjektiv/Adverb'),
('einverstanden', 'de acuerdo', 3, 'Verb'),
('laufen', 'andar; correr', 4, 'Verb'),
('das Fahrrad', 'bicicleta', 4, 'Nomen'),
('Fahrrad fahren', 'ir en bicicleta', 4, 'Verb'),
('schwimmen', 'nadar', 4, 'Verb'),
('Fußball spielen', 'jugar al fútbol', 4, 'Verb'),
('das Hobby', 'hobby; afición', 4, 'Nomen'),
('ins Theater gehen', 'ir al teatro', 4, 'Verb'),
('fernsehen', 'ver la televisión', 4, 'Verb'),
('Klavier spielen', 'tocar el piano', 4, 'Verb'),
('tanzen', 'bailar', 4, 'Verb'),
('reisen', 'viajar; turismo', 4, 'Verb'),
('Sport machen', 'hacer deporte', 4, 'Verb'),
('das Fitnessstudio', 'gimnasio', 4, 'Nomen'),
('das Team', 'equipo', 4, 'Nomen'),
('das Spiel', 'juego; partido', 4, 'Nomen'),
('spielen', 'jugar', 4, 'Verb'),
('der Muskelkater', 'agujetas', 4, 'Nomen'),
('der Start', 'inicio; arranque', 4, 'Nomen'),
('das Ziel', 'meta', 4, 'Nomen'),
('der Sieg', 'victoria', 4, 'Nomen'),
('die Anzeige', 'anuncio', 4, 'Nomen'),
('die Zeitung', 'periódico', 4, 'Nomen'),
('das Kind', 'niño', 4, 'Nomen'),
('der Jugendliche', 'adolescente', 4, 'Nomen'),
('der Erwachsene', 'adulto', 4, 'Nomen'),
('der Rentner', 'jubilado', 4, 'Nomen'),
('das Gefühl', 'sensación', 4, 'Nomen'),
('das Interesse', 'interés', 4, 'Nomen'),
('die Sache / das Ding', 'cosa; objeto', 4, 'Nomen'),
('der Schuh', 'zapato', 4, 'Nomen'),
('der Schüler', 'alumno', 4, 'Nomen'),
('bekommen / erhalten', 'obtener; recibir', 4, 'Verb'),
('bezahlen', 'pagar', 4, 'Verb'),
('erlauben', 'permitir', 4, 'Verb'),
('verbieten', 'prohibir', 4, 'Verb'),
('fahren', 'ir (en vehículo)', 4, 'Verb'),
('funktionieren', 'funcionar', 4, 'Verb'),
('schaffen', 'crear algo; conseguir algo', 4, 'Verb'),
('schlafen', 'dormir', 4, 'Verb'),
('suchen', 'buscar', 4, 'Verb'),
('sich treffen', 'encontrarse', 4, 'Verb'),
('wissen', 'saber', 4, 'Verb'),
('begeistert', 'entusiasmado', 4, 'Adjektiv/Adverb'),
('zufrieden', 'contento', 4, 'Verb'),
('wunderbar', 'maravilloso', 4, 'Adjektiv/Adverb'),
('jährlich', 'anual', 4, 'Adjektiv/Adverb'),
('offen', 'abierto', 4, 'Adjektiv/Adverb'),
('regelmäßig', 'regularmente', 4, 'Adjektiv/Adverb'),
('gut', 'bien; a gusto', 4, 'Adjektiv/Adverb'),
('besser', 'mejor; más a gusto', 4, 'Adjektiv/Adverb'),
('schauen / ansehen', 'mirar; contemplar', 5, 'Verb'),
('wechseln', 'cambiar', 5, 'Verb'),
('breit', 'ancho', 5, 'Adjektiv/Adverb'),
('richtig', 'correcto', 5, 'Adjektiv/Adverb'),
('auf keinen Fall', 'de ninguna manera', 5, 'Ausdruck'),
('bis', 'hasta', 5, 'Adjektiv/Adverb'),
('wohnen', 'residir; vivir', 5, 'Verb'),
('das Haus', 'casa', 5, 'Nomen'),
('die Wohnung', 'piso', 5, 'Nomen'),
('die WG', 'piso compartido', 5, 'Nomen'),
('der Bewohner', 'habitante', 5, 'Nomen'),
('der Mitbewohner', 'compañero de piso', 5, 'Nomen'),
('die Miete', 'alquiler', 5, 'Nomen'),
('der Mieter', 'inquilino', 5, 'Nomen'),
('der Vermieter', 'casero', 5, 'Nomen'),
('mieten', 'alquilar', 5, 'Verb'),
('der Eingang', 'entrada', 5, 'Nomen'),
('die Badewanne', 'bañera', 5, 'Nomen'),
('das Fenster', 'ventana', 5, 'Nomen'),
('einziehen', 'mudarse (entrar)', 5, 'Verb'),
('ausziehen', 'mudarse (salir)', 5, 'Verb'),
('möblieren', 'amueblar', 5, 'Verb'),
('die Größe', 'tamaño', 5, 'Nomen'),
('das Bett', 'cama', 5, 'Nomen'),
('der Schrank', 'armario', 5, 'Nomen'),
('der Küchentisch', 'mesa de cocina', 5, 'Nomen'),
('das Glas', 'vidrio', 5, 'Nomen'),
('die Nachricht', 'noticia', 5, 'Nomen'),
('der Stau', 'atasco', 5, 'Nomen'),
('abholen', 'recoger', 5, 'Verb'),
('öffnen', 'abrir', 5, 'Verb'),
('anrufen', 'llamar', 5, 'Verb'),
('benutzen', 'usar', 5, 'Verb'),
('beschreiben', 'describir', 5, 'Verb'),
('denken / glauben', 'pensar; creer', 5, 'Verb'),
('sprechen', 'hablar', 5, 'Verb'),
('stehen', 'estar de pie', 5, 'Verb'),
('vergessen', 'olvidar', 5, 'Verb'),
('verwenden', 'usar; emplear', 5, 'Verb'),
('billig', 'barato', 5, 'Adjektiv/Adverb'),
('groß', 'grande', 5, 'Adjektiv/Adverb'),
('frei', 'libre', 5, 'Adjektiv/Adverb'),
('gesund', 'sano', 5, 'Adjektiv/Adverb'),
('krank', 'enfermo', 5, 'Adjektiv/Adverb'),
('kalt', 'frío', 5, 'Adjektiv/Adverb'),
('spät', 'tarde', 5, 'Adjektiv/Adverb'),
('gestern', 'ayer', 5, 'Verb'),
('lange', 'mucho tiempo', 5, 'Adjektiv/Adverb'),
('vielleicht', 'quizás', 5, 'Adjektiv/Adverb'),
('zu teuer', 'demasiado caro', 5, 'Ausdruck'),
('die Kleidung', 'ropa; vestimenta', 6, 'Nomen'),
('die Hose', 'pantalón', 6, 'Nomen'),
('der Mantel', 'abrigo', 6, 'Nomen'),
('die Jacke', 'chaqueta', 6, 'Nomen'),
('der Anzug', 'traje', 6, 'Nomen'),
('das Hemd', 'camisa', 6, 'Nomen'),
('die Bluse', 'blusa', 6, 'Nomen'),
('der Rock', 'falda', 6, 'Nomen'),
('die Unterhose', 'calzoncillos', 6, 'Nomen'),
('die Socke', 'calcetín', 6, 'Nomen'),
('der Gürtel', 'cinturón', 6, 'Nomen'),
('der Handschuh', 'guante', 6, 'Nomen'),
('die Mütze', 'gorro', 6, 'Nomen'),
('die Farbe', 'color', 6, 'Nomen'),
('rot', 'rojo', 6, 'Adjektiv/Adverb'),
('schwarz', 'negro', 6, 'Adjektiv/Adverb'),
('das Leder', 'piel; cuero', 6, 'Nomen'),
('die Wolle', 'lana', 6, 'Nomen'),
('waschen', 'lavar', 6, 'Verb'),
('die Wäsche', 'colada', 6, 'Nomen'),
('die Waschmaschine', 'lavadora', 6, 'Nomen'),
('das Waschpulver', 'detergente', 6, 'Nomen'),
('trocknen', 'secar', 6, 'Verb'),
('öffnen', 'abrir', 6, 'Verb'),
('schließen', 'cerrar', 6, 'Verb'),
('einlaufen', 'encogerse', 6, 'Verb'),
('die Angst', 'miedo', 6, 'Nomen'),
('die Beschreibung', 'descripción', 6, 'Nomen'),
('der Tee', 'té', 6, 'Nomen'),
('der Besitzer', 'propietario', 6, 'Nomen'),
('die Lösung', 'solución', 6, 'Nomen'),
('die Notiz', 'apunte; nota', 6, 'Nomen'),
('der Platz', 'plaza; sitio', 6, 'Nomen'),
('der Traum', 'sueño', 6, 'Nomen'),
('die Tür', 'puerta', 6, 'Nomen'),
('der Wunsch', 'deseo', 6, 'Nomen'),
('die Zeile', 'línea; fila', 6, 'Nomen'),
('anfangen', 'empezar', 6, 'Verb'),
('aufpassen', 'prestar atención', 6, 'Verb'),
('bedeuten', 'significar', 6, 'Verb'),
('einladen', 'invitar', 6, 'Verb'),
('sich entschuldigen', 'disculparse', 6, 'Verb'),
('erklären', 'explicar', 6, 'Verb'),
('fernsehen', 'ver la tele', 6, 'Verb'),
('sagen', 'decir', 6, 'Verb'),
('träumen', 'soñar', 6, 'Verb'),
('vermuten', 'sospechar; suponer', 6, 'Verb'),
('versuchen', 'intentar', 6, 'Verb'),
('fertig', 'listo', 6, 'Adjektiv/Adverb'),
('langsam', 'despacio', 6, 'Adjektiv/Adverb'),
('das Verkehrsmittel', 'medio de transporte', 7, 'Nomen'),
('die Bahn', 'tren', 7, 'Nomen'),
('die Straßenbahn', 'tranvía', 7, 'Nomen'),
('zu Fuß gehen', 'ir a pie', 7, 'Verb'),
('abbiegen', 'girar', 7, 'Verb'),
('aussteigen', 'bajarse', 7, 'Verb'),
('der Bahnhof', 'estación', 7, 'Nomen'),
('die Fahrkarte', 'billete', 7, 'Nomen'),
('der Ort', 'lugar', 7, 'Nomen'),
('die Ecke', 'esquina', 7, 'Nomen'),
('das Gebäude', 'edificio', 7, 'Nomen'),
('die Kirche', 'iglesia', 7, 'Nomen'),
('die Regierung', 'gobierno', 7, 'Nomen'),
('der Turm', 'torre', 7, 'Nomen'),
('besichtigen', 'visitar; inspeccionar', 7, 'Verb'),
('der Stadtplan', 'plano de la ciudad', 7, 'Nomen'),
('der Weg', 'camino', 7, 'Nomen'),
('die Kreuzung', 'cruce', 7, 'Nomen'),
('der Platz', 'plaza', 7, 'Nomen'),
('die Wegbeschreibung', 'indicaciones', 7, 'Nomen'),
('geradeaus', 'todo recto', 7, 'Adjektiv/Adverb'),
('rechts', 'derecha', 7, 'Adjektiv/Adverb'),
('links', 'izquierda', 7, 'Adjektiv/Adverb'),
('das Bild', 'imagen', 7, 'Nomen'),
('der Künstler', 'artista', 7, 'Nomen'),
('das Gemälde', 'pintura', 7, 'Nomen'),
('die Blume', 'flor', 7, 'Nomen'),
('die Ehe', 'matrimonio', 7, 'Nomen'),
('die Einladung', 'invitación', 7, 'Nomen'),
('das Einkaufszentrum', 'centro comercial', 7, 'Nomen'),
('das Ende', 'final', 7, 'Nomen'),
('der Fehler', 'error', 7, 'Nomen'),
('die Gegenwart', 'presente', 7, 'Nomen'),
('die Vergangenheit', 'pasado', 7, 'Nomen'),
('die Zukunft', 'futuro', 7, 'Nomen'),
('das Geld', 'dinero', 7, 'Nomen'),
('das Geschenk', 'regalo', 7, 'Nomen'),
('beenden', 'terminar', 7, 'Verb'),
('danken', 'agradecer', 7, 'Verb'),
('gehören', 'pertenecer', 7, 'Verb'),
('heiraten', 'casarse', 7, 'Verb'),
('leben', 'vivir', 7, 'Verb'),
('sterben', 'morir', 7, 'Verb'),
('unterrichten', 'enseñar', 7, 'Verb'),
('einfach', 'simple', 7, 'Adjektiv/Adverb'),
('lustig', 'divertido', 7, 'Adjektiv/Adverb'),
('traurig', 'triste', 7, 'Adjektiv/Adverb'),
('früher', 'antes', 7, 'Adjektiv/Adverb'),
('etwas', 'algo', 7, 'Adjektiv/Adverb'),
('das nächste Mal', 'la próxima vez', 7, 'Nomen'),
('die Suppe', 'sopa', 8, 'Nomen'),
('das Huhn', 'pollo', 8, 'Nomen'),
('das Öl', 'aceite', 8, 'Nomen'),
('die Sauce', 'salsa', 8, 'Nomen'),
('die Torte', 'tarta', 8, 'Nomen'),
('die Zitrone', 'limón', 8, 'Nomen'),
('die Birne', 'pera', 8, 'Nomen'),
('bitter', 'amargo', 8, 'Adjektiv/Adverb'),
('salzig', 'salado', 8, 'Adjektiv/Adverb'),
('süß', 'dulce', 8, 'Adjektiv/Adverb'),
('scharf', 'picante', 8, 'Adjektiv/Adverb'),
('sauer', 'ácido', 8, 'Adjektiv/Adverb'),
('fettig', 'graso', 8, 'Adjektiv/Adverb'),
('die Speise', 'plato (comida)', 8, 'Nomen'),
('die Nachspeise', 'postre', 8, 'Nomen'),
('die Speisekarte', 'carta', 8, 'Nomen'),
('der Gast', 'cliente', 8, 'Nomen'),
('die Rechnung', 'cuenta', 8, 'Nomen'),
('das Trinkgeld', 'propina', 8, 'Nomen'),
('geschlossen sein', 'estar cerrado', 8, 'Verb'),
('offen sein', 'estar abierto', 8, 'Verb'),
('bestellen', 'pedir', 8, 'Verb'),
('genießen', 'disfrutar', 8, 'Verb'),
('die Gabel', 'tenedor', 8, 'Nomen'),
('das Messer', 'cuchillo', 8, 'Nomen'),
('der Teller', 'plato', 8, 'Nomen'),
('die Tasse', 'taza', 8, 'Nomen'),
('das Glas', 'vaso', 8, 'Nomen'),
('das Weinglas', 'copa de vino', 8, 'Nomen'),
('der Topf', 'olla', 8, 'Nomen'),
('das Gericht', 'plato preparado', 8, 'Nomen'),
('die Zubereitung', 'preparación', 8, 'Nomen'),
('die Ablehnung', 'rechazo', 8, 'Nomen'),
('die Zustimmung', 'aprobación', 8, 'Nomen'),
('das Gegenteil', 'contrario', 8, 'Nomen'),
('die Hilfe', 'ayuda', 8, 'Nomen'),
('die Kohlensäure', 'gas', 8, 'Nomen'),
('das Lieblingsessen', 'comida favorita', 8, 'Nomen'),
('die Station', 'parada', 8, 'Nomen'),
('eröffnen', 'inaugurar', 8, 'Verb'),
('lieben', 'amar', 8, 'Verb'),
('getrennt', 'separado', 8, 'Adjektiv/Adverb'),
('laut', 'ruidoso', 8, 'Adjektiv/Adverb'),
('leise', 'en voz baja', 8, 'Adjektiv/Adverb'),
('draußen', 'fuera', 8, 'Verb'),
('drinnen', 'dentro', 8, 'Verb'),
('überall', 'en todas partes', 8, 'Adjektiv/Adverb'),
('ohne', 'sin', 8, 'Adjektiv/Adverb'),
('was ist los?', '¿qué pasa?', 8, 'Adjektiv/Adverb'),
('es tut mir leid', 'lo siento', 8, 'Adjektiv/Adverb'),
('die Tradition', 'costumbre', 9, 'Nomen'),
('das Fest', 'fiesta', 9, 'Nomen'),
('Weihnachten', 'Navidad', 9, 'Nomen'),
('der Baum', 'árbol', 9, 'Nomen'),
('der Heiligabend', 'Nochebuena', 9, 'Nomen'),
('die Kerze', 'vela', 9, 'Nomen'),
('Ostern', 'Pascua', 9, 'Nomen'),
('das Neujahrsfest', 'Año Nuevo', 9, 'Nomen'),
('Silvester', 'Nochevieja', 9, 'Nomen'),
('die Geburt', 'nacimiento', 9, 'Nomen'),
('der Tod', 'muerte', 9, 'Nomen'),
('typisch sein für', 'ser típico', 9, 'Verb'),
('die Absage', 'rechazo', 9, 'Nomen'),
('die Zusage', 'confirmación', 9, 'Nomen'),
('das Dorf', 'pueblo', 9, 'Nomen'),
('das Feuer', 'fuego', 9, 'Nomen'),
('das Gästezimmer', 'habitación de invitados', 9, 'Nomen'),
('der Garten', 'jardín', 9, 'Nomen'),
('das Geschäft', 'tienda', 9, 'Nomen'),
('der Himmel', 'cielo', 9, 'Nomen'),
('die Hoffnung', 'esperanza', 9, 'Nomen'),
('die Krankheit', 'enfermedad', 9, 'Nomen'),
('der Mond', 'luna', 9, 'Nomen'),
('der Nachbar / die Nachbarin', 'vecino', 9, 'Nomen'),
('der Teil', 'parte', 9, 'Nomen'),
('das Zelt', 'tienda de campaña', 9, 'Nomen'),
('vermuten', 'suponer', 9, 'Verb'),
('brechen', 'romper', 9, 'Verb'),
('reservieren', 'reservar', 9, 'Verb'),
('sich erinnern an', 'recordar', 9, 'Verb'),
('sprechen über', 'hablar sobre', 9, 'Verb'),
('übernachten', 'pasar la noche', 9, 'Verb'),
('verstecken', 'esconder', 9, 'Verb'),
('vorhaben', 'tener planes', 9, 'Verb'),
('vorschlagen', 'proponer', 9, 'Verb'),
('zusammenhängen mit', 'estar relacionado', 9, 'Verb'),
('unhöflich', 'maleducado', 9, 'Adjektiv/Adverb'),
('gemeinsam', 'en común', 9, 'Adjektiv/Adverb'),
('gemütlich', 'acogedor', 9, 'Adjektiv/Adverb'),
('wahrscheinlich', 'probablemente', 9, 'Adjektiv/Adverb'),
('wichtig', 'importante', 9, 'Adjektiv/Adverb'),
('kaum', 'apenas', 9, 'Adjektiv/Adverb'),
('manchmal', 'a veces', 9, 'Adjektiv/Adverb'),
('mehrmals', 'varias veces', 9, 'Adjektiv/Adverb'),
('unbedingt', 'imprescindible', 9, 'Adjektiv/Adverb'),
('wem?', '¿a quién?', 9, 'Adjektiv/Adverb'),
('teilweise', 'en parte', 9, 'Adjektiv/Adverb'),
('die Lage', 'situación; ubicación', 10, 'Nomen'),
('das Viertel', 'barrio', 10, 'Nomen'),
('der Verkehr', 'tráfico', 10, 'Nomen'),
('die Verkehrsverbindung', 'conexión de transporte', 10, 'Nomen'),
('die Haltestelle', 'parada', 10, 'Nomen'),
('außerhalb', 'fuera de', 10, 'Adjektiv/Adverb'),
('ruhig', 'tranquilo', 10, 'Adjektiv/Adverb'),
('die Kaltmiete', 'alquiler en frío', 10, 'Nomen'),
('die Nebenkosten', 'gastos adicionales', 10, 'Nomen'),
('die Kaution', 'fianza', 10, 'Nomen'),
('die Hausordnung', 'reglamento de la casa', 10, 'Nomen'),
('der Mietvertrag', 'contrato de alquiler', 10, 'Nomen'),
('ausfüllen', 'rellenar', 10, 'Verb'),
('der Familienstand', 'estado civil', 10, 'Nomen'),
('ledig', 'soltero', 10, 'Adjektiv/Adverb'),
('verheiratet', 'casado', 10, 'Adjektiv/Adverb'),
('geschieden', 'divorciado', 10, 'Verb'),
('der Einzugstermin', 'fecha de entrada', 10, 'Nomen'),
('das Hochhaus', 'edificio comercial', 10, 'Nomen'),
('der Aufzug', 'ascensor', 10, 'Nomen'),
('der Hof', 'patio', 10, 'Nomen'),
('der Parkplatz', 'aparcamiento', 10, 'Nomen'),
('die Mülltonne', 'contenedor de basura', 10, 'Nomen'),
('der Abstellraum', 'trastero', 10, 'Nomen'),
('das Schlafzimmer', 'dormitorio', 10, 'Nomen'),
('die Wand', 'pared', 10, 'Nomen'),
('der Kamin', 'chimenea', 10, 'Nomen'),
('der Boden', 'suelo', 10, 'Nomen'),
('die Decke', 'techo', 10, 'Nomen'),
('die Steckdose', 'enchufe', 10, 'Nomen'),
('der Süden', 'sur', 10, 'Nomen'),
('der Norden', 'norte', 10, 'Nomen'),
('der Abschied', 'despedida', 10, 'Nomen'),
('das Allgemeine', 'general', 10, 'Nomen'),
('die Höhe', 'altura', 10, 'Nomen'),
('das Kaufhaus', 'grandes almacenes', 10, 'Nomen'),
('der Lärm', 'jaleo', 10, 'Nomen'),
('die Stelle', 'puesto de trabajo', 10, 'Nomen'),
('der Müll', 'basura', 10, 'Nomen'),
('die Seite', 'lado', 10, 'Nomen'),
('die Sicherheit', 'seguridad', 10, 'Nomen'),
('der Vorteil', 'ventaja', 10, 'Nomen'),
('klingeln', 'sonar (timbre)', 10, 'Verb'),
('teilen', 'compartir', 10, 'Verb'),
('wirken', 'parecer', 10, 'Verb'),
('flach', 'plano', 10, 'Adjektiv/Adverb'),
('ab jetzt', 'a partir de ahora', 10, 'Ausdruck'),
('mehrere', 'varios', 10, 'Adjektiv/Adverb'),
('zwischen', 'entre', 10, 'Verb'),
('das Gebäude', 'edificio', 11, 'Nomen'),
('die Kneipe', 'bar', 11, 'Nomen'),
('die Universität', 'universidad', 11, 'Nomen'),
('das Studium', 'estudios', 11, 'Nomen'),
('die Gebühr', 'tasa', 11, 'Nomen'),
('das Wohnheim', 'residencia', 11, 'Nomen'),
('das Hochdeutsch', 'alemán estándar', 11, 'Nomen'),
('das Interview', 'entrevista', 11, 'Nomen'),
('einräumen', 'ordenar', 11, 'Verb'),
('ausräumen', 'vaciar', 11, 'Verb'),
('der Alltag', 'vida cotidiana', 11, 'Nomen'),
('der Besucher', 'visitante', 11, 'Nomen'),
('die Erfahrung', 'experiencia', 11, 'Nomen'),
('die Heizkosten', 'costes de calefacción', 11, 'Nomen'),
('die Sparkasse', 'caja de ahorros', 11, 'Nomen'),
('der Zeitpunkt', 'momento', 11, 'Nomen'),
('anbieten', 'ofrecer', 11, 'Verb'),
('abschließen', 'terminar', 11, 'Verb'),
('klarmachen', 'aclarar', 11, 'Verb'),
('sich erholen von', 'recuperarse', 11, 'Verb'),
('sich erinnern', 'recordar', 11, 'Verb'),
('sich erkälten', 'resfriarse', 11, 'Verb'),
('erkennen', 'reconocer', 11, 'Verb'),
('sich fühlen', 'sentirse', 11, 'Verb'),
('hoffen', 'esperar', 11, 'Verb'),
('kennenlernen', 'conocer', 11, 'Verb'),
('klagen', 'quejarse', 11, 'Verb'),
('meinen', 'opinar', 11, 'Verb'),
('sich merken', 'memorizar', 11, 'Verb'),
('sich sorgen', 'preocuparse', 11, 'Verb'),
('sich verändern', 'cambiar', 11, 'Verb'),
('verbessern', 'mejorar', 11, 'Verb'),
('weggehen', 'irse', 11, 'Verb'),
('gewöhnlich', 'cotidiano', 11, 'Adjektiv/Adverb'),
('anstrengend', 'agotador', 11, 'Adjektiv/Adverb'),
('ausländisch', 'extranjero', 11, 'Adjektiv/Adverb'),
('einsam', 'solo', 11, 'Adjektiv/Adverb'),
('gering', 'escaso', 11, 'Adjektiv/Adverb'),
('nächster', 'siguiente', 11, 'Adjektiv/Adverb'),
('außerdem', 'además', 11, 'Adjektiv/Adverb'),
('inzwischen', 'mientras tanto', 11, 'Verb'),
('meistens', 'la mayoría de las veces', 11, 'Adjektiv/Adverb'),
('mindestens', 'al menos', 11, 'Adjektiv/Adverb'),
('aktuell', 'actualmente', 11, 'Adjektiv/Adverb'),
('einige', 'algunos', 11, 'Adjektiv/Adverb'),
('schließlich', 'al final', 11, 'Adjektiv/Adverb'),
('die Bank', 'banco', 12, 'Nomen'),
('der Kunde', 'cliente', 12, 'Nomen'),
('der Geldautomat', 'cajero automático', 12, 'Nomen'),
('das Bargeld', 'dinero en efectivo', 12, 'Nomen'),
('der Betrag', 'cantidad', 12, 'Nomen'),
('die Quittung', 'recibo', 12, 'Nomen'),
('das Konto', 'cuenta', 12, 'Nomen'),
('die Kontonummer', 'número de cuenta', 12, 'Nomen'),
('die Geheimzahl', 'PIN', 12, 'Nomen'),
('einzahlen', 'ingresar', 12, 'Verb'),
('ein Konto eröffnen', 'abrir cuenta', 12, 'Verb'),
('sperren', 'bloquear', 12, 'Verb'),
('kostenlos', 'gratis', 12, 'Adjektiv/Adverb'),
('kurzfristig', 'a corto plazo', 12, 'Adjektiv/Adverb'),
('die Karte einstecken', 'introducir tarjeta', 12, 'Nomen'),
('PIN eingeben', 'introducir PIN', 12, 'Verb'),
('die Karte herausnehmen', 'sacar tarjeta', 12, 'Nomen'),
('die Anzeige', 'pantalla', 12, 'Nomen'),
('anzeigen', 'denunciar', 12, 'Verb'),
('der Dieb', 'ladrón', 12, 'Nomen'),
('das Geschlecht', 'sexo', 12, 'Nomen'),
('der Erfolg', 'éxito', 12, 'Nomen'),
('der Fachbegriff', 'tecnicismo', 12, 'Nomen'),
('die Firma', 'empresa', 12, 'Nomen'),
('die Freiheit', 'libertad', 12, 'Nomen'),
('der Richter', 'juez', 12, 'Nomen'),
('der Treffpunkt', 'punto de encuentro', 12, 'Nomen'),
('die Verwendung', 'uso', 12, 'Nomen'),
('der Zweck', 'objetivo', 12, 'Nomen'),
('abgeben', 'entregar', 12, 'Verb'),
('raten', 'aconsejar', 12, 'Verb'),
('Bescheid sagen', 'avisar', 12, 'Verb'),
('betrügen', 'engañar', 12, 'Verb'),
('einsammeln', 'recoger', 12, 'Verb'),
('sich freuen', 'alegrarse', 12, 'Verb'),
('merken', 'notar', 12, 'Verb'),
('rauchen', 'fumar', 12, 'Verb'),
('stimmen', 'estar correcto', 12, 'Verb'),
('prüfen', 'examinar', 12, 'Verb'),
('vereinbaren', 'acordar', 12, 'Verb'),
('verlieren', 'perder', 12, 'Verb'),
('vertrauen', 'confiar', 12, 'Verb'),
('wachsen', 'crecer', 12, 'Verb'),
('arm', 'pobre', 12, 'Adjektiv/Adverb'),
('bekannt', 'conocido', 12, 'Adjektiv/Adverb'),
('ganz', 'completamente', 12, 'Adjektiv/Adverb'),
('genau', 'exacto', 12, 'Adjektiv/Adverb'),
('plötzlich', 'de repente', 12, 'Adjektiv/Adverb'),
('der Arm', 'brazo', 13, 'Nomen'),
('das Auge', 'ojo', 13, 'Nomen'),
('der Bauch', 'vientre; barriga', 13, 'Nomen'),
('das Bein', 'pierna', 13, 'Nomen'),
('der Finger', 'dedo', 13, 'Nomen'),
('die Lunge', 'pulmón', 13, 'Nomen'),
('der Mund', 'boca', 13, 'Nomen'),
('der Rücken', 'espalda', 13, 'Nomen'),
('der Körper', 'cuerpo', 13, 'Nomen'),
('die Krankheit', 'enfermedad', 13, 'Nomen'),
('die Gesundheit', 'salud', 13, 'Nomen'),
('das Fieber', 'fiebre', 13, 'Nomen'),
('der Schmerz', 'dolor', 13, 'Nomen'),
('fehlen', 'faltar', 13, 'Verb'),
('wehtun', 'doler', 13, 'Adjektiv/Adverb'),
('der Patient', 'paciente', 13, 'Nomen'),
('die Krankenversicherung', 'seguro médico', 13, 'Nomen'),
('die Versichertenkarte', 'tarjeta sanitaria', 13, 'Nomen'),
('versichert sein', 'estar asegurado', 13, 'Verb'),
('der Raucher', 'fumador', 13, 'Nomen'),
('die Behandlung', 'tratamiento', 13, 'Nomen'),
('die Operation', 'operación', 13, 'Nomen'),
('das Medikament', 'medicamento', 13, 'Nomen'),
('der Tropfen', 'gota', 13, 'Nomen'),
('die Dosierung', 'dosificación', 13, 'Nomen'),
('die Wirkung', 'efecto', 13, 'Nomen'),
('heilen', 'curar', 13, 'Verb'),
('die Abteilung', 'departamento', 13, 'Nomen'),
('die Dauer', 'duración', 13, 'Nomen'),
('die Empfehlung', 'recomendación', 13, 'Nomen'),
('die Entwicklung', 'desarrollo', 13, 'Nomen'),
('der Dienst', 'servicio', 13, 'Nomen'),
('die Spätschicht', 'turno de tarde', 13, 'Nomen'),
('das Gerät', 'aparato', 13, 'Nomen'),
('die Müdigkeit', 'cansancio', 13, 'Nomen'),
('die Schwangerschaft', 'embarazo', 13, 'Nomen'),
('der Termin', 'cita', 13, 'Nomen'),
('die Vertretung', 'sustitución', 13, 'Nomen'),
('sich bemühen', 'esforzarse', 13, 'Verb'),
('sich ausruhen', 'descansar', 13, 'Verb'),
('entdecken', 'descubrir', 13, 'Verb'),
('passieren', 'pasar', 13, 'Verb'),
('dauerhaft', 'permanente', 13, 'Adjektiv/Adverb'),
('erfahren', 'experimentado', 13, 'Verb'),
('häufig', 'frecuente', 13, 'Adjektiv/Adverb'),
('notwendig', 'necesario', 13, 'Adjektiv/Adverb'),
('täglich', 'diario', 13, 'Adjektiv/Adverb'),
('tagsüber', 'de día', 13, 'Adjektiv/Adverb'),
('eigen', 'propio', 13, 'Verb'),
('der Wetterbericht', 'parte meteorológico', 14, 'Nomen'),
('der Sturm', 'tormenta', 14, 'Nomen'),
('der Nebel', 'niebla', 14, 'Nomen'),
('der Schnee', 'nieve', 14, 'Nomen'),
('scheinen', 'brillar', 14, 'Verb'),
('stürmen', 'haber tormenta', 14, 'Verb'),
('schneien', 'nevar', 14, 'Verb'),
('sonnig', 'soleado', 14, 'Adjektiv/Adverb'),
('klar', 'despejado', 14, 'Adjektiv/Adverb'),
('regnerisch', 'lluvioso', 14, 'Adjektiv/Adverb'),
('die Kleidung', 'ropa', 14, 'Nomen'),
('die Jacke', 'chaqueta', 14, 'Nomen'),
('der Ärmel', 'manga', 14, 'Nomen'),
('der Ausschnitt', 'escote', 14, 'Nomen'),
('der Rollkragen', 'cuello alto', 14, 'Nomen'),
('die Größe', 'talla', 14, 'Nomen'),
('die Handtasche', 'bolso', 14, 'Nomen'),
('die Abteilung', 'departamento', 14, 'Nomen'),
('die Umkleidekabine', 'probador', 14, 'Nomen'),
('der Kassenzettel', 'ticket', 14, 'Nomen'),
('das Wechselgeld', 'cambio', 14, 'Nomen'),
('unbequem', 'incómodo', 14, 'Adjektiv/Adverb'),
('bunt', 'multicolor', 14, 'Adjektiv/Adverb'),
('schön', 'bonito', 14, 'Adjektiv/Adverb'),
('hässlich', 'feo', 14, 'Adjektiv/Adverb'),
('die Ware', 'mercancía', 14, 'Nomen'),
('das Bierzelt', 'carpa de cerveza', 14, 'Nomen'),
('das Volksfest', 'fiesta popular', 14, 'Nomen'),
('die Schaukel', 'columpio', 14, 'Nomen'),
('der Bürgermeister', 'alcalde', 14, 'Nomen'),
('der Absatz', 'párrafo', 14, 'Nomen'),
('die Bedeutung', 'significado', 14, 'Nomen'),
('die Erinnerung', 'memoria', 14, 'Nomen'),
('der Geschmack', 'sabor', 14, 'Nomen'),
('die Hochzeit', 'boda', 14, 'Nomen'),
('das Malbuch', 'libro para colorear', 14, 'Nomen'),
('die Umgebung', 'alrededores', 14, 'Nomen'),
('der Umsatz', 'ventas', 14, 'Nomen'),
('entwickeln', 'desarrollar', 14, 'Verb'),
('benutzen', 'usar', 14, 'Verb'),
('warnen', 'advertir', 14, 'Verb'),
('übersetzen', 'traducir', 14, 'Verb'),
('ernst', 'serio', 14, 'Adjektiv/Adverb'),
('fröhlich', 'alegre', 14, 'Adjektiv/Adverb'),
('kaputt', 'roto', 14, 'Adjektiv/Adverb'),
('unterschiedlich', 'diferente', 14, 'Adjektiv/Adverb'),
('schließlich', 'finalmente', 14, 'Adjektiv/Adverb'),
('mal so, mal so', 'a veces sí / a veces no', 14, 'Adjektiv/Adverb'),
('vorne', 'delante', 14, 'Adjektiv/Adverb'),
('zum ersten Mal', 'por primera vez', 14, 'Adjektiv/Adverb'),
('die Übernachtung', 'pernoctación', 15, 'Nomen'),
('der Gastgeber', 'anfitrión', 15, 'Nomen'),
('die Fahrt', 'viaje', 15, 'Nomen'),
('die Grenze', 'frontera', 15, 'Nomen'),
('der Grenzübergang', 'paso fronterizo', 15, 'Nomen'),
('die Maut', 'peaje', 15, 'Nomen'),
('parken', 'aparcar', 15, 'Verb'),
('das Parkhaus', 'parking', 15, 'Nomen'),
('die Tankstelle', 'gasolinera', 15, 'Nomen'),
('die Fahrkarte', 'billete', 15, 'Nomen'),
('die Fahrkarte', 'ticket', 15, 'Nomen'),
('die Dauerkarte', 'abono', 15, 'Nomen'),
('die Entwertung', 'cancelación', 15, 'Nomen'),
('der Spaziergang', 'paseo', 15, 'Nomen'),
('die Vorstellung', 'función', 15, 'Nomen'),
('der Hauptdarsteller', 'protagonista', 15, 'Nomen'),
('der Flohmarkt', 'mercadillo', 15, 'Nomen'),
('die Staatsoper', 'ópera estatal', 15, 'Nomen'),
('abbiegen', 'girar', 15, 'Verb'),
('folgen', 'seguir', 15, 'Verb'),
('überqueren', 'cruzar', 15, 'Verb'),
('der Moment', 'momento', 15, 'Nomen'),
('der Besitzer', 'propietario', 15, 'Nomen'),
('das Fernsehen', 'televisión', 15, 'Nomen'),
('die Gelegenheit', 'oportunidad', 15, 'Nomen'),
('die Beobachtung', 'observación', 15, 'Nomen'),
('der Kiosk', 'kiosco', 15, 'Nomen'),
('der Reisende', 'viajero', 15, 'Nomen'),
('der Plan', 'plan', 15, 'Nomen'),
('das Hobby', 'afición', 15, 'Nomen'),
('verstehen', 'entender', 15, 'Verb'),
('entscheiden', 'decidir', 15, 'Verb'),
('einsteigen', 'subir', 15, 'Verb'),
('sich melden', 'avisar', 15, 'Verb'),
('nachdenken', 'reflexionar', 15, 'Verb'),
('stammen aus', 'proceder de', 15, 'Verb'),
('stattfinden', 'tener lugar', 15, 'Verb'),
('verbinden', 'conectar', 15, 'Verb'),
('anschließend', 'a continuación', 15, 'Adjektiv/Adverb'),
('spannend', 'emocionante', 15, 'Adjektiv/Adverb'),
('beliebig', 'arbitrario', 15, 'Adjektiv/Adverb'),
('faul', 'perezoso', 15, 'Adjektiv/Adverb'),
('gültig', 'válido', 15, 'Adjektiv/Adverb'),
('golden', 'dorado', 15, 'Verb'),
('kompliziert', 'complicado', 15, 'Adjektiv/Adverb'),
('weltberühmt', 'de fama mundial', 15, 'Adjektiv/Adverb'),
('kostenlos', 'gratis', 15, 'Adjektiv/Adverb'),
('unterwegs', 'de camino', 15, 'Adjektiv/Adverb'),
('übrigens', 'por cierto', 15, 'Adjektiv/Adverb'),
('das heißt', 'o sea', 15, 'Nomen'),
('die Ausbildung', 'formación', 16, 'Nomen'),
('die duale Ausbildung', 'formación dual', 16, 'Nomen'),
('die Berufsausbildung', 'formación profesional', 16, 'Nomen'),
('der Auszubildende', 'aprendiz', 16, 'Nomen'),
('der Unterricht', 'clase', 16, 'Nomen'),
('das Schuljahr', 'curso escolar', 16, 'Nomen'),
('das Abitur', 'bachillerato', 16, 'Nomen'),
('arbeitslos', 'desempleado', 16, 'Adjektiv/Adverb'),
('der Beruf', 'profesión', 16, 'Nomen'),
('die Berufserfahrung', 'experiencia laboral', 16, 'Nomen'),
('beruflich', 'profesional', 16, 'Adjektiv/Adverb'),
('handwerklich', 'artesanal', 16, 'Adjektiv/Adverb'),
('der Übersetzer', 'traductor', 16, 'Nomen'),
('die Beratung', 'asesoramiento', 16, 'Nomen'),
('das Praktikum', 'prácticas', 16, 'Nomen'),
('das Gehalt', 'salario', 16, 'Nomen'),
('das Einkommen', 'ingresos', 16, 'Nomen'),
('die Pflege', 'cuidado', 16, 'Nomen'),
('der Haushalt', 'hogar', 16, 'Nomen'),
('die Bewegung', 'movimiento', 16, 'Nomen'),
('die Analyse', 'análisis', 16, 'Nomen'),
('die Einleitung', 'introducción', 16, 'Nomen'),
('das Ende', 'final', 16, 'Nomen'),
('berücksichtigen', 'tener en cuenta', 16, 'Verb'),
('das Ergebnis', 'resultado', 16, 'Nomen'),
('erarbeiten', 'elaborar', 16, 'Verb'),
('die Gesellschaft', 'sociedad', 16, 'Nomen'),
('die Medien', 'medios', 16, 'Nomen'),
('die Politik', 'política', 16, 'Nomen'),
('das Tagebuch', 'diario', 16, 'Nomen'),
('sicher', 'seguro', 16, 'Adjektiv/Adverb'),
('empfehlen', 'recomendar', 16, 'Verb'),
('sich entscheiden', 'decidirse', 16, 'Verb'),
('enttäuschen', 'decepcionar', 16, 'Verb'),
('erwarten', 'esperar', 16, 'Verb'),
('reichen', 'ser suficiente', 16, 'Verb'),
('überrascht', 'estar sorprendido', 16, 'Adjektiv/Adverb'),
('vergehen', 'pasar', 16, 'Verb'),
('zuhören', 'escuchar', 16, 'Verb'),
('abhängig', 'dependiente', 16, 'Adjektiv/Adverb'),
('bisher', 'hasta ahora', 16, 'Adjektiv/Adverb'),
('geduldig', 'paciente', 16, 'Adjektiv/Adverb'),
('gleichzeitig', 'simultáneamente', 16, 'Adjektiv/Adverb'),
('leicht', 'ligero', 16, 'Adjektiv/Adverb'),
('schwer', 'pesado', 16, 'Adjektiv/Adverb'),
('sinnvoll', 'con sentido', 16, 'Adjektiv/Adverb'),
('verantwortlich', 'responsable', 16, 'Adjektiv/Adverb'),
('neulich', 'hace poco', 16, 'Adjektiv/Adverb'),
('die Bewerbung', 'solicitud', 17, 'Nomen'),
('sich bewerben', 'solicitar', 17, 'Verb'),
('das Vorstellungsgespräch', 'entrevista de trabajo', 17, 'Nomen'),
('die Herstellung', 'fabricación', 17, 'Nomen'),
('die Fabrik', 'fábrica', 17, 'Nomen'),
('die Industrie', 'industria', 17, 'Nomen'),
('der Stoff', 'materia', 17, 'Nomen'),
('die Verpackung', 'embalaje', 17, 'Nomen'),
('der Mitarbeiter', 'trabajador', 17, 'Nomen'),
('beschäftigen', 'emplear', 17, 'Verb'),
('der Verkauf', 'venta', 17, 'Nomen'),
('die Arbeitszeit', 'jornada laboral', 17, 'Nomen'),
('die Gleitzeit', 'horario flexible', 17, 'Nomen'),
('die Schicht', 'turno', 17, 'Nomen'),
('die Nachtschicht', 'turno de noche', 17, 'Nomen'),
('die Überstunde', 'hora extra', 17, 'Nomen'),
('der Schwerpunkt', 'punto clave', 17, 'Nomen'),
('die Leistung', 'rendimiento', 17, 'Nomen'),
('die Note', 'nota', 17, 'Nomen'),
('die Kenntnisse', 'conocimiento', 17, 'Nomen'),
('die Qualifikation', 'competencia', 17, 'Nomen'),
('das Pflichtfach', 'parte obligatoria', 17, 'Nomen'),
('abschließen', 'terminar', 17, 'Verb'),
('der Absatz', 'párrafo', 17, 'Nomen'),
('das Thema', 'tema', 17, 'Nomen'),
('der Brief', 'carta', 17, 'Nomen'),
('der Besitzer', 'propietario', 17, 'Nomen'),
('die Eröffnung', 'inauguración', 17, 'Nomen'),
('die Gründung', 'fundación', 17, 'Nomen'),
('die Kontrolle', 'control', 17, 'Nomen'),
('das Geschäft', 'tienda', 17, 'Nomen'),
('der Rabatt', 'descuento', 17, 'Nomen'),
('die Art', 'tipo', 17, 'Nomen'),
('die Erhöhung', 'aumento', 17, 'Nomen'),
('die Umgangssprache', 'lenguaje coloquial', 17, 'Nomen'),
('die Voraussetzung', 'condición', 17, 'Nomen'),
('verlassen', 'abandonar', 17, 'Verb'),
('beifügen', 'adjuntar', 17, 'Verb'),
('erleben', 'experimentar', 17, 'Verb'),
('festlegen', 'establecer', 17, 'Verb'),
('teilnehmen', 'participar', 17, 'Verb'),
('überprüfen', 'comprobar', 17, 'Verb'),
('vorbereiten', 'preparar', 17, 'Verb'),
('allgemein', 'general', 17, 'Adjektiv/Adverb'),
('erfolgreich', 'exitoso', 17, 'Adjektiv/Adverb'),
('freiwillig', 'voluntario', 17, 'Adjektiv/Adverb'),
('gleich', 'igual', 17, 'Adjektiv/Adverb'),
('üblich', 'habitual', 17, 'Adjektiv/Adverb'),
('vertraut', 'familiar', 17, 'Adjektiv/Adverb'),
('zusätzlich', 'adicional', 17, 'Adjektiv/Adverb'),
('die Landschaft', 'paisaje', 18, 'Nomen'),
('das Meer', 'mar', 18, 'Nomen'),
('die Insel', 'isla', 18, 'Nomen'),
('der Strand', 'playa', 18, 'Nomen'),
('die Luft', 'aire', 18, 'Nomen'),
('die Pflanze', 'planta', 18, 'Nomen'),
('das Schiff', 'barco', 18, 'Nomen'),
('der Hafen', 'puerto', 18, 'Nomen'),
('die Kreuzfahrt', 'crucero', 18, 'Nomen'),
('die Ferne', 'lejanía', 18, 'Nomen'),
('die Hochsaison', 'temporada alta', 18, 'Nomen'),
('die Unterkunft', 'alojamiento', 18, 'Nomen'),
('die Verpflegung', 'alimentación', 18, 'Nomen'),
('der Wohnwagen', 'caravana', 18, 'Nomen'),
('das Doppelzimmer', 'habitación doble', 18, 'Nomen'),
('die Vollpension', 'pensión completa', 18, 'Nomen'),
('das Buffet', 'bufé', 18, 'Nomen'),
('sich entspannen', 'relajar', 18, 'Verb'),
('das Erlebnis', 'experiencia', 18, 'Nomen'),
('faulenzen', 'vaguear', 18, 'Verb'),
('klettern', 'escalar', 18, 'Verb'),
('segeln', 'navegar', 18, 'Verb'),
('springen', 'saltar', 18, 'Verb'),
('der Aufbau', 'montaje', 18, 'Nomen'),
('der Abbau', 'desmontaje', 18, 'Nomen'),
('das Ereignis', 'acontecimiento', 18, 'Nomen'),
('der Geist', 'espíritu', 18, 'Nomen'),
('der Hunger', 'hambre', 18, 'Nomen'),
('das Zentrum', 'centro', 18, 'Nomen'),
('das Nichts', 'la nada', 18, 'Nomen'),
('der Unsinn', 'tontería', 18, 'Nomen'),
('der Rand', 'borde', 18, 'Nomen'),
('die Sendung', 'programa', 18, 'Nomen'),
('die Spur', 'pista', 18, 'Nomen'),
('die Versorgung', 'abastecimiento', 18, 'Nomen'),
('ankommen', 'llegar', 18, 'Verb'),
('fliegen', 'volar', 18, 'Verb'),
('sich lohnen', 'merecer la pena', 18, 'Verb'),
('schreien', 'gritar', 18, 'Verb'),
('aushalten', 'aguantar', 18, 'Verb'),
('jung', 'joven', 18, 'Adjektiv/Adverb'),
('weit', 'lejos', 18, 'Adjektiv/Adverb'),
('kühl', 'fresco', 18, 'Adjektiv/Adverb'),
('klar', 'claro', 18, 'Adjektiv/Adverb'),
('vielfältig', 'variado', 18, 'Adjektiv/Adverb'),
('danach', 'después', 18, 'Adjektiv/Adverb'),
('nirgendwo', 'en ninguna parte', 18, 'Adjektiv/Adverb'),
('sogar', 'incluso', 18, 'Adjektiv/Adverb'),
('sonst', 'por lo demás', 18, 'Adjektiv/Adverb'),
('gern', 'a gusto', 18, 'Verb'),
('das Reisebüro', 'agencia de viajes', 19, 'Nomen'),
('der Pass', 'pasaporte', 19, 'Nomen'),
('der Personalausweis', 'DNI', 19, 'Nomen'),
('das Ausland', 'extranjero', 19, 'Nomen'),
('der Aufenthalt', 'estancia', 19, 'Nomen'),
('die Verbindung', 'conexión', 19, 'Nomen'),
('die Abfahrt', 'salida', 19, 'Nomen'),
('landen', 'aterrizar', 19, 'Verb'),
('die Reservierung', 'reserva', 19, 'Nomen'),
('stornieren', 'anular', 19, 'Verb'),
('der Flughafen', 'aeropuerto', 19, 'Nomen'),
('das Gate', 'puerta de embarque', 19, 'Nomen'),
('das Gleis', 'andén', 19, 'Nomen'),
('das Gepäck', 'equipaje', 19, 'Nomen'),
('der Koffer', 'maleta', 19, 'Nomen'),
('der Rucksack', 'mochila', 19, 'Nomen'),
('das Regierungssystem', 'sistema de gobierno', 19, 'Nomen'),
('der Staat', 'estado', 19, 'Nomen'),
('das Bundesland', 'estado federado', 19, 'Nomen'),
('die Gemeinde', 'municipio', 19, 'Nomen'),
('der Abgeordnete', 'diputado', 19, 'Nomen'),
('demokratisch', 'democrático', 19, 'Adjektiv/Adverb'),
('die Bevölkerung', 'población', 19, 'Nomen'),
('der Einwohner', 'habitante', 19, 'Nomen'),
('der Fluss', 'río', 19, 'Nomen'),
('die Wut', 'enfado', 19, 'Nomen'),
('die Aktivität', 'actividad', 19, 'Nomen'),
('die Information', 'información', 19, 'Nomen'),
('der Blick', 'vista', 19, 'Nomen'),
('die Hälfte', 'mitad', 19, 'Nomen'),
('praktisch', 'en la práctica', 19, 'Adjektiv/Adverb'),
('die Schrift', 'carta / escrito', 19, 'Nomen'),
('sich anmelden', 'registrarse', 19, 'Verb'),
('bestätigen', 'confirmar', 19, 'Verb'),
('bilden', 'formar', 19, 'Verb'),
('enden', 'terminar', 19, 'Verb'),
('fließen', 'fluir', 19, 'Verb'),
('geschehen', 'ocurrir', 19, 'Verb'),
('neugierig sein', 'tener curiosidad', 19, 'Verb'),
('leihen', 'pedir prestado', 19, 'Verb'),
('reagieren', 'reaccionar', 19, 'Verb'),
('stören', 'molestar', 19, 'Verb'),
('verlängern', 'prolongar', 19, 'Verb'),
('zusammenfassen', 'resumir', 19, 'Verb'),
('nötig', 'necesario', 19, 'Adjektiv/Adverb'),
('unbekannt', 'desconocido', 19, 'Adjektiv/Adverb'),
('unsicher', 'inseguro', 19, 'Adjektiv/Adverb'),
('verschieden', 'diferente', 19, 'Verb'),
('ungefähr', 'aproximadamente', 19, 'Adjektiv/Adverb'),
('hiermit', 'por la presente', 19, 'Adjektiv/Adverb'),
('danach', 'después', 20, 'Adjektiv/Adverb'),
('der Unfall', 'accidente', 20, 'Nomen'),
('der Verkehrsunfall', 'accidente de tráfico', 20, 'Nomen'),
('handeln', 'actuar', 20, 'Verb'),
('überholen', 'adelantar', 20, 'Verb'),
('gerade', 'recto', 20, 'Adjektiv/Adverb'),
('erreichbar', 'alcanzable', 20, 'Adjektiv/Adverb'),
('der Rettungswagen', 'ambulancia', 20, 'Nomen'),
('Jahre alt', 'edad', 20, 'Verb'),
('versichern', 'asegurar', 20, 'Verb'),
('sich wundern', 'sorprenderse', 20, 'Verb'),
('feststellen', 'constatar', 20, 'Verb'),
('wütend', 'enfadado', 20, 'Adjektiv/Adverb'),
('wechseln auf', 'cambiar a', 20, 'Verb'),
('die Gegenfahrbahn', 'carril contrario', 20, 'Nomen'),
('verursachen', 'causar', 20, 'Verb'),
('die Rücksichtslosigkeit', 'chulería', 20, 'Nomen'),
('der Zusammenstoß', 'colisión', 20, 'Nomen'),
('die Folge', 'consecuencia', 20, 'Nomen'),
('kontinuierlich', 'continuo', 20, 'Adjektiv/Adverb'),
('die Rippe', 'costilla', 20, 'Nomen'),
('schuldig', 'culpable', 20, 'Adjektiv/Adverb'),
('Erste Hilfe leisten', 'primeros auxilios', 20, 'Verb'),
('die Aussage', 'declaración', 20, 'Nomen'),
('die Richtung', 'dirección', 20, 'Nomen'),
('der Streit', 'discusión', 20, 'Nomen'),
('einschlafen', 'quedarse dormido', 20, 'Verb'),
('der Schuldige', 'culpable', 20, 'Nomen'),
('der Verletzte', 'herido', 20, 'Nomen'),
('der Verrückte', 'loco', 20, 'Nomen'),
('der Tote', 'muerto', 20, 'Nomen'),
('der Notfall', 'emergencia', 20, 'Nomen'),
('der Zustand', 'estado', 20, 'Nomen'),
('beteiligt sein', 'estar implicado', 20, 'Verb'),
('ausweichen', 'esquivar', 20, 'Verb'),
('bremsen', 'frenar', 20, 'Verb'),
('die Bremse', 'freno', 20, 'Nomen'),
('wütend', 'furioso', 20, 'Adjektiv/Adverb'),
('die Wunde', 'herida', 20, 'Nomen'),
('berichten', 'informar', 20, 'Verb'),
('die Strafe', 'multa', 20, 'Nomen'),
('die Haut', 'piel', 20, 'Nomen'),
('die Brücke', 'puente', 20, 'Nomen'),
('sich verspäten', 'llegar tarde', 20, 'Verb'),
('brechen', 'romper', 20, 'Verb'),
('übersehen', 'pasar por alto', 20, 'Verb'),
('überraschen', 'sorprender', 20, 'Verb'),
('schuld sein an', 'tener la culpa', 20, 'Verb'),
('der Zeuge', 'testigo', 20, 'Nomen'),
('die Ansicht', 'aspecto', 21, 'Nomen'),
('die Fassade', 'fachada', 21, 'Nomen'),
('die Runde', 'vuelta', 21, 'Nomen'),
('der Ausbildungsgang', 'carrera', 21, 'Nomen'),
('der Designer', 'diseñador', 21, 'Nomen'),
('das Management', 'gestión', 21, 'Nomen'),
('die Medien', 'medios', 21, 'Nomen'),
('das Schauspiel', 'teatro', 21, 'Nomen'),
('der Schauspieler', 'actor', 21, 'Nomen'),
('die Bühne', 'escenario', 21, 'Nomen'),
('das Kapitel', 'capítulo', 21, 'Nomen'),
('der Sänger', 'cantante', 21, 'Nomen'),
('das Argument', 'argumento', 21, 'Nomen'),
('der Bart', 'barba', 21, 'Nomen'),
('die Branche', 'sector', 21, 'Nomen'),
('das Abendessen', 'cena', 21, 'Nomen'),
('das Engagement', 'compromiso', 21, 'Nomen'),
('die Fläche', 'superficie', 21, 'Nomen'),
('die Form', 'forma', 21, 'Nomen'),
('der Frühaufsteher', 'madrugador', 21, 'Nomen'),
('das Gesicht', 'cara', 21, 'Nomen'),
('die Schönheit', 'belleza', 21, 'Nomen'),
('die Verteidigung', 'defensa', 21, 'Nomen'),
('ausbilden', 'formar', 21, 'Verb'),
('begleiten', 'acompañar', 21, 'Verb'),
('schützen', 'proteger', 21, 'Verb'),
('besorgt sein', 'preocuparse', 21, 'Adjektiv/Adverb'),
('einfallen', 'ocurrir (venir a la mente)', 21, 'Verb'),
('erwischen', 'pillar', 21, 'Verb'),
('fliehen', 'huir', 21, 'Verb'),
('sich konzentrieren auf', 'concentrarse', 21, 'Verb'),
('bekommen', 'recibir', 21, 'Verb'),
('orientiert sein an', 'orientarse', 21, 'Verb'),
('recht haben', 'tener razón', 21, 'Verb'),
('retten', 'salvar', 21, 'Verb'),
('trennen', 'separar', 21, 'Verb'),
('treten', 'pisar', 21, 'Verb'),
('unternehmen', 'emprender', 21, 'Verb'),
('verpassen', 'perderse', 21, 'Verb'),
('verschwinden', 'desaparecer', 21, 'Verb'),
('zurückkommen', 'volver', 21, 'Verb'),
('blond', 'rubio', 21, 'Adjektiv/Adverb'),
('ehemalig', 'antiguo', 21, 'Adjektiv/Adverb'),
('einzig', 'único', 21, 'Adjektiv/Adverb'),
('hart', 'duro', 21, 'Adjektiv/Adverb'),
('aktuell', 'actual', 21, 'Adjektiv/Adverb'),
('die Post', 'correos', 22, 'Nomen'),
('das Postamt', 'oficina de correos', 22, 'Nomen'),
('der Briefträger', 'cartero', 22, 'Nomen'),
('der Einschreibebrief', 'carta certificada', 22, 'Nomen'),
('senden', 'enviar', 22, 'Verb'),
('die Sendung', 'envío', 22, 'Nomen'),
('der Absender', 'remitente', 22, 'Nomen'),
('der Empfänger', 'destinatario', 22, 'Nomen'),
('die Zustellung', 'entrega', 22, 'Nomen'),
('einwerfen', 'echar (al buzón)', 22, 'Verb'),
('das Haustier', 'mascota', 22, 'Nomen'),
('der Beleg', 'comprobante', 22, 'Nomen'),
('die Beschwerde', 'queja', 22, 'Nomen'),
('das Geheimnis', 'secreto', 22, 'Nomen'),
('das Heimweh', 'nostalgia', 22, 'Nomen'),
('das Inland', 'interior del país', 22, 'Nomen'),
('die Panne', 'avería', 22, 'Nomen'),
('die Reaktion', 'reacción', 22, 'Nomen'),
('die Strafe', 'penalización', 22, 'Nomen'),
('der Verlag', 'editorial', 22, 'Nomen'),
('der Verlobte', 'prometido', 22, 'Nomen'),
('der Wert', 'valor', 22, 'Nomen'),
('die Zeitschrift', 'revista', 22, 'Nomen'),
('der Fernseher', 'televisor', 22, 'Nomen'),
('die Europäische Union', 'Unión Europea', 22, 'Nomen'),
('die Garantie', 'garantía', 22, 'Nomen'),
('die Mitteilung', 'mensaje', 22, 'Nomen'),
('die Webseite', 'página web', 22, 'Nomen'),
('der Werktag', 'día laborable', 22, 'Nomen'),
('abstimmen mit', 'coordinar', 22, 'Verb'),
('angeben', 'indicar', 22, 'Verb'),
('sich beschweren über', 'quejarse', 22, 'Verb'),
('einkaufen', 'comprar', 22, 'Verb'),
('betreffen', 'afectar', 22, 'Verb'),
('sich kümmern um', 'ocuparse', 22, 'Verb'),
('realisieren', 'darse cuenta', 22, 'Verb'),
('verfolgen', 'perseguir', 22, 'Verb'),
('verreisen', 'viajar', 22, 'Verb'),
('versprechen', 'prometer', 22, 'Verb'),
('verstärken', 'reforzar', 22, 'Verb'),
('emotional', 'emocional', 22, 'Adjektiv/Adverb'),
('ordentlich', 'ordenado', 22, 'Adjektiv/Adverb'),
('pünktlich', 'puntual', 22, 'Adjektiv/Adverb'),
('tot', 'muerto', 22, 'Adjektiv/Adverb'),
('damals', 'entonces', 22, 'Adjektiv/Adverb'),
('solche', 'tal', 22, 'Adjektiv/Adverb'),
('in Ordnung sein', 'estar en orden', 22, 'Verb'),
('die Hochschule', 'escuela superior', 23, 'Nomen'),
('der Bachelor', 'grado', 23, 'Nomen'),
('die Promotion', 'doctorado', 23, 'Nomen'),
('die Aufnahmeprüfung', 'prueba de acceso', 23, 'Nomen'),
('die Lehre', 'enseñanza', 23, 'Nomen'),
('die Wissenschaft', 'ciencia', 23, 'Nomen'),
('sich immatrikulieren', 'matricularse', 23, 'Verb'),
('die Germanistik', 'filología alemana', 23, 'Nomen'),
('Jura', 'derecho', 23, 'Nomen'),
('der Analytiker', 'analista', 23, 'Nomen'),
('der Dolmetscher', 'intérprete', 23, 'Nomen'),
('die Kunst', 'arte', 23, 'Nomen'),
('das Instrument', 'instrumento', 23, 'Nomen'),
('die Begabung', 'talento', 23, 'Nomen'),
('das Berufsleben', 'vida profesional', 23, 'Nomen'),
('die Besonderheit', 'característica', 23, 'Nomen'),
('die Fähigkeit', 'capacidad', 23, 'Nomen'),
('die Jugend', 'juventud', 23, 'Nomen'),
('der Lebensweg', 'trayectoria', 23, 'Nomen'),
('die Leidenschaft', 'pasión', 23, 'Nomen'),
('die Praxis', 'práctica', 23, 'Nomen'),
('die Theorie', 'teoría', 23, 'Nomen'),
('der Vortrag', 'conferencia', 23, 'Nomen'),
('prüfen', 'comprobar', 23, 'Verb'),
('überlegen', 'pensar', 23, 'Verb'),
('verwandeln', 'convertir', 23, 'Verb'),
('anerkannt', 'reconocido', 23, 'Adjektiv/Adverb'),
('üblich', 'habitual', 23, 'Adjektiv/Adverb'),
('künstlerisch', 'artístico', 23, 'Adjektiv/Adverb'),
('pädagogisch', 'pedagógico', 23, 'Adjektiv/Adverb'),
('theoretisch', 'teórico', 23, 'Adjektiv/Adverb'),
('praxisorientiert', 'práctico', 23, 'Adjektiv/Adverb'),
('selbstständig', 'independiente', 23, 'Adjektiv/Adverb'),
('wegen', 'debido a', 23, 'Verb'),
('zuerst', 'en primer lugar', 23, 'Adjektiv/Adverb'),
('auf diese Weise', 'de esta manera', 23, 'Ausdruck'),
('in der Regel', 'por regla general', 23, 'Ausdruck'),
('die Psychologie', 'psicología', 23, 'Nomen'),
('der Oberarzt', 'médico jefe', 23, 'Nomen'),
('die Wärme', 'calor', 23, 'Nomen'),
('der Kompass', 'brújula', 23, 'Nomen'),
('das Unternehmen', 'empresa', 23, 'Nomen'),
('aufwachsen', 'crecer', 23, 'Verb'),
('fürchten', 'temer', 23, 'Verb'),
('gesamt', 'total', 23, 'Adjektiv/Adverb'),
('gleichzeitig', 'al mismo tiempo', 23, 'Adjektiv/Adverb'),
('der Bauernhof', 'granja', 24, 'Nomen'),
('der Stall', 'establo', 24, 'Nomen'),
('die Weide', 'prado', 24, 'Nomen'),
('anbauen', 'cultivar', 24, 'Verb'),
('biologisch', 'biológico', 24, 'Adjektiv/Adverb'),
('ökologisch', 'ecológico', 24, 'Adjektiv/Adverb'),
('die Umwelt', 'medio ambiente', 24, 'Nomen'),
('der Umweltschutz', 'protección ambiental', 24, 'Nomen'),
('ernten', 'cosechar', 24, 'Verb'),
('füttern', 'alimentar', 24, 'Verb'),
('die Aufgabe', 'misión', 24, 'Nomen'),
('das Mitglied', 'miembro', 24, 'Nomen'),
('die Stiftung', 'fundación', 24, 'Nomen'),
('freiwillig', 'voluntario', 24, 'Adjektiv/Adverb'),
('der Esel', 'burro', 24, 'Nomen'),
('das Huhn', 'pollo', 24, 'Nomen'),
('die Kuh', 'vaca', 24, 'Nomen'),
('die Ziege', 'cabra', 24, 'Nomen'),
('fressen', 'comer (animal)', 24, 'Verb'),
('der Zivildienst', 'servicio civil', 24, 'Nomen'),
('gemeinnützig', 'sin ánimo de lucro', 24, 'Adjektiv/Adverb'),
('die Anfrage', 'consulta', 24, 'Nomen'),
('der Betreuer', 'cuidador', 24, 'Nomen'),
('die Betreuung', 'cuidado', 24, 'Nomen'),
('bewerten', 'evaluar', 24, 'Verb'),
('der Entschluss', 'decisión', 24, 'Nomen'),
('die Erwartung', 'expectativa', 24, 'Nomen'),
('der Fachmann', 'experto', 24, 'Nomen'),
('die Freundschaft', 'amistad', 24, 'Nomen'),
('die Handarbeit', 'manualidad', 24, 'Nomen'),
('die Lebensweise', 'forma de vida', 24, 'Nomen'),
('der Strom', 'corriente eléctrica', 24, 'Nomen'),
('das Taschengeld', 'dinero de bolsillo', 24, 'Nomen'),
('unterbringen', 'alojar', 24, 'Verb'),
('vermarkten', 'comercializar', 24, 'Verb'),
('verpflegen', 'alimentar', 24, 'Verb'),
('das Modell', 'modelo', 24, 'Nomen'),
('der Zusammenhang', 'relación', 24, 'Nomen'),
('beurteilen', 'juzgar', 24, 'Verb'),
('sich entschließen zu', 'decidirse', 24, 'Verb'),
('erhalten', 'recibir', 24, 'Verb'),
('gewohnt sein', 'estar acostumbrado', 24, 'Verb'),
('schweigen', 'callarse', 24, 'Verb'),
('sich verlassen auf', 'confiar', 24, 'Verb'),
('dankbar', 'agradecido', 24, 'Adjektiv/Adverb'),
('die Begrüßung', 'saludo', 25, 'Nomen'),
('die Geste', 'gesto', 25, 'Nomen'),
('der Handschlag', 'apretón de manos', 25, 'Nomen'),
('der Kuss', 'beso', 25, 'Nomen'),
('nicken', 'asentir', 25, 'Verb'),
('die Umarmung', 'abrazo', 25, 'Nomen'),
('winken', 'hacer señas', 25, 'Verb'),
('der Small Talk', 'conversación trivial', 25, 'Nomen'),
('der Ausdruck', 'expresión', 25, 'Nomen'),
('die Redewendung', 'frase hecha', 25, 'Nomen'),
('wörtlich', 'literalmente', 25, 'Adjektiv/Adverb'),
('nachschlagen', 'consultar', 25, 'Verb'),
('übertragen', 'transmitir', 25, 'Verb'),
('der Anlass', 'motivo', 25, 'Nomen'),
('der Empfang', 'recepción', 25, 'Nomen'),
('die Kälte', 'frío', 25, 'Nomen'),
('die Leitung', 'dirección', 25, 'Nomen'),
('die Panik', 'pánico', 25, 'Nomen'),
('das Pech', 'mala suerte', 25, 'Nomen'),
('antworten', 'responder', 25, 'Verb'),
('begründen', 'justificar', 25, 'Verb'),
('inserieren', 'poner anuncio', 25, 'Verb'),
('vermeiden', 'evitar', 25, 'Verb'),
('deprimiert', 'deprimido', 25, 'Adjektiv/Adverb'),
('vornehm', 'distinguido', 25, 'Adjektiv/Adverb'),
('sich begrüßen', 'saludarse', 25, 'Verb'),
('der Wangenkuss', 'beso en la mejilla', 25, 'Nomen'),
('die Korrektur', 'corrección', 25, 'Nomen'),
('der Auszug', 'extracto', 25, 'Nomen'),
('die Fortsetzung', 'continuación', 25, 'Nomen'),
('das Meeting', 'reunión', 25, 'Nomen'),
('der Mut', 'valor', 25, 'Nomen'),
('der Ratgeber', 'guía', 25, 'Nomen'),
('die Schwierigkeit', 'dificultad', 25, 'Nomen'),
('der Sekt', 'champán', 25, 'Nomen'),
('die Umgangsformen', 'modales', 25, 'Nomen'),
('die Ursache', 'causa', 25, 'Nomen'),
('das Verständnis', 'comprensión', 25, 'Nomen'),
('das Vertrauen', 'confianza', 25, 'Nomen'),
('abhängen von', 'depender', 25, 'Verb'),
('sich beschäftigen mit', 'ocuparse', 25, 'Verb'),
('üben', 'practicar', 25, 'Verb'),
('unangenehm', 'desagradable', 25, 'Adjektiv/Adverb'),
('formell', 'formal', 25, 'Adjektiv/Adverb'),
('hochachtungsvoll', 'atentamente', 25, 'Adjektiv/Adverb'),
('ausgezeichnet', 'excelente', 25, 'Adjektiv/Adverb'),
('gegenseitig', 'mutuamente', 25, 'Adjektiv/Adverb'),
('teilweise', 'parcialmente', 25, 'Adjektiv/Adverb'),
('überhaupt nicht', 'en absoluto', 25, 'Adjektiv/Adverb'),
('ungefähr', 'aproximadamente', 25, 'Adjektiv/Adverb'),
('der Arbeitsvertrag', 'contrato laboral', 26, 'Nomen'),
('der Arbeitnehmer', 'empleado', 26, 'Nomen'),
('das Verhältnis', 'relación', 26, 'Nomen'),
('die Arbeitszeit', 'tiempo de trabajo', 26, 'Nomen'),
('die Stelle', 'puesto', 26, 'Nomen'),
('die Geschäftsführung', 'dirección', 26, 'Nomen'),
('der Lohn', 'salario', 26, 'Nomen'),
('die Frist', 'plazo', 26, 'Nomen'),
('unterschreiben', 'firmar', 26, 'Verb'),
('einstellen', 'contratar', 26, 'Verb'),
('tätig sein als', 'trabajar como', 26, 'Adjektiv/Adverb'),
('das Werk', 'fábrica', 26, 'Nomen'),
('der Prozess', 'proceso', 26, 'Nomen'),
('das Passwort', 'contraseña', 26, 'Nomen'),
('der Anspruch', 'derecho', 26, 'Nomen'),
('der Antrag', 'solicitud', 26, 'Nomen'),
('der Urlaubsantrag', 'vacaciones', 26, 'Nomen'),
('das Infobrett', 'tablón', 26, 'Nomen'),
('die Brille', 'gafas', 26, 'Nomen'),
('die Lesebrille', 'gafas de lectura', 26, 'Nomen'),
('gemäß', 'según', 26, 'Adjektiv/Adverb'),
('die Herkunft', 'origen', 26, 'Nomen'),
('die Kraft', 'fuerza', 26, 'Nomen'),
('der Krieg', 'guerra', 26, 'Nomen'),
('der Laptop', 'ordenador portátil', 26, 'Nomen'),
('die Nachfrage', 'demanda', 26, 'Nomen'),
('der Sand', 'arena', 26, 'Nomen'),
('die Verwaltung', 'administración', 26, 'Nomen'),
('die Wanderung', 'excursión', 26, 'Nomen'),
('die Zusammenfassung', 'resumen', 26, 'Nomen'),
('achten auf', 'atender', 26, 'Verb'),
('auszahlen', 'pagar', 26, 'Verb'),
('durchlesen', 'leer completamente', 26, 'Verb'),
('lassen', 'dejar', 26, 'Verb'),
('verschieben', 'posponer', 26, 'Verb'),
('sorgen für', 'cuidar de', 26, 'Verb'),
('bedecken', 'cubrir', 26, 'Verb'),
('vertreten', 'representar', 26, 'Verb'),
('zukommen lassen', 'hacer llegar', 26, 'Verb'),
('zulassen', 'permitir', 26, 'Verb'),
('vollständig', 'completo', 26, 'Adjektiv/Adverb'),
('schriftlich', 'por escrito', 26, 'Adjektiv/Adverb'),
('zuständig', 'responsable', 26, 'Adjektiv/Adverb'),
('beziehungsweise', 'respectivamente', 26, 'Adjektiv/Adverb'),
('anschließend', 'a continuación', 26, 'Adjektiv/Adverb'),
('der Zeitraum', 'período', 27, 'Nomen'),
('die Revolution', 'revolución', 27, 'Nomen'),
('die Nation', 'nación', 27, 'Nomen'),
('die Hauptstadt', 'capital', 27, 'Nomen'),
('die Weltwirtschaftskrise', 'crisis económica mundial', 27, 'Nomen'),
('die Macht', 'poder', 27, 'Nomen'),
('die Zerstörung', 'destrucción', 27, 'Nomen'),
('das Opfer', 'víctima', 27, 'Nomen'),
('die Flucht', 'huida', 27, 'Nomen'),
('umkommen', 'morir', 27, 'Verb'),
('die Mauer', 'muro', 27, 'Nomen'),
('die Teilung', 'división', 27, 'Nomen'),
('die Wiedervereinigung', 'reunificación', 27, 'Nomen'),
('der Schriftsteller', 'escritor', 27, 'Nomen'),
('das Blut', 'sangre', 27, 'Nomen'),
('die Blüte', 'floración', 27, 'Nomen'),
('der Charme', 'encanto', 27, 'Nomen'),
('das Denkmal', 'monumento', 27, 'Nomen'),
('die Entdeckung', 'descubrimiento', 27, 'Nomen'),
('der Erfinder', 'inventor', 27, 'Nomen'),
('die Galerie', 'galería', 27, 'Nomen'),
('der Imbiss', 'comida rápida', 27, 'Nomen'),
('das Jahrzehnt', 'década', 27, 'Nomen'),
('der Kindergarten', 'guardería', 27, 'Nomen'),
('die Krise', 'crisis', 27, 'Nomen'),
('der Ruhm', 'fama', 27, 'Nomen'),
('das Schicksal', 'destino', 27, 'Nomen'),
('die Staatsbürgerschaft', 'ciudadanía', 27, 'Nomen'),
('das Schwimmbad', 'piscina', 27, 'Nomen'),
('der Verlust', 'pérdida', 27, 'Nomen'),
('die Multiplikation', 'multiplicación', 27, 'Nomen'),
('die Volkshochschule', 'escuela popular', 27, 'Nomen'),
('der Vorhang', 'cortina', 27, 'Nomen'),
('die Wahrheit', 'verdad', 27, 'Nomen'),
('die Wirklichkeit', 'realidad', 27, 'Nomen'),
('in Wirklichkeit', 'en realidad', 27, 'Ausdruck'),
('der Zahn', 'diente', 27, 'Nomen'),
('anziehen', 'ponerse ropa', 27, 'Verb'),
('sich vorstellen', 'imaginar', 27, 'Verb'),
('erfinden', 'inventar', 27, 'Verb'),
('gehören zu', 'formar parte', 27, 'Verb'),
('umbauen', 'reconstruir', 27, 'Verb'),
('verstecken', 'ocultar', 27, 'Verb'),
('wiedererkennen', 'reconocer', 27, 'Verb'),
('chaotisch', 'caótico', 27, 'Adjektiv/Adverb'),
('tatsächlich', 'realmente', 27, 'Adjektiv/Adverb'),
('während', 'mientras', 27, 'Adjektiv/Adverb'),
('der Einwanderer', 'inmigrante', 28, 'Nomen'),
('die Ausreise', 'salida', 28, 'Nomen'),
('die Rückkehr', 'regreso', 28, 'Nomen'),
('der Flüchtling', 'refugiado', 28, 'Nomen'),
('die Heimat', 'patria', 28, 'Nomen'),
('das Heimweh', 'morriña', 28, 'Nomen'),
('jeder Zweite', 'uno de cada dos', 28, 'Adjektiv/Adverb'),
('doppelt', 'doble', 28, 'Adjektiv/Adverb'),
('die Absicht', 'intención', 28, 'Nomen'),
('die Armut', 'pobreza', 28, 'Nomen'),
('die Umfrage', 'encuesta', 28, 'Nomen'),
('die Chance', 'oportunidad', 28, 'Nomen'),
('das Risiko', 'riesgo', 28, 'Nomen'),
('die Entscheidung', 'decisión', 28, 'Nomen'),
('die Erlaubnis', 'permiso', 28, 'Nomen'),
('die Fachkraft', 'especialista', 28, 'Nomen'),
('das Gesetz', 'ley', 28, 'Nomen'),
('die Herausforderung', 'reto', 28, 'Nomen'),
('die Klarheit', 'claridad', 28, 'Nomen'),
('das Klima', 'clima', 28, 'Nomen'),
('der Koch', 'cocinero', 28, 'Nomen'),
('die Lebenshaltung', 'nivel de vida', 28, 'Nomen'),
('der Kurs', 'curso', 28, 'Nomen'),
('das Niveau', 'nivel', 28, 'Nomen'),
('das Lohnniveau', 'nivel salarial', 28, 'Nomen'),
('die Lebensumstände', 'circunstancia', 28, 'Nomen'),
('die Zuversicht', 'confianza', 28, 'Nomen'),
('gelingen', 'lograr', 28, 'Verb'),
('wichtig finden', 'valorar', 28, 'Verb'),
('sich Mut machen', 'animarse', 28, 'Verb'),
('Fragen stellen', 'preguntar', 28, 'Verb'),
('vermissen', 'echar de menos', 28, 'Verb'),
('organisieren', 'gestionar', 28, 'Verb'),
('weitergehen', 'continuar', 28, 'Verb'),
('bürokratisch', 'burocrático', 28, 'Adjektiv/Adverb'),
('mittelalterlich', 'medieval', 28, 'Adjektiv/Adverb'),
('sichtbar', 'visible', 28, 'Adjektiv/Adverb'),
('umfassend', 'completo', 28, 'Adjektiv/Adverb'),
('am Anfang', 'al principio', 28, 'Ausdruck'),
('woanders', 'en otro lugar', 28, 'Adjektiv/Adverb'),
('lüften', 'ventilar', 28, 'Verb'),
('sich entspannen', 'relajarse', 28, 'Verb'),
('einheimisch', 'nativo', 28, 'Adjektiv/Adverb'),
('geheimnisvoll', 'misterioso', 28, 'Adjektiv/Adverb'),
('mental', 'mental', 28, 'Adjektiv/Adverb'),
('sogenannt', 'llamado', 28, 'Adjektiv/Adverb'),
('kürzlich', 'recientemente', 28, 'Adjektiv/Adverb'),
('das System', 'sistema', 29, 'Nomen'),
('die Staatsform', 'forma de estado', 29, 'Nomen'),
('die Bundesrepublik', 'república federal', 29, 'Nomen'),
('der Bundestag', 'parlamento', 29, 'Nomen'),
('repräsentativ', 'representativo', 29, 'Adjektiv/Adverb'),
('der Kanzler', 'canciller', 29, 'Nomen'),
('der Präsident', 'presidente', 29, 'Nomen'),
('die Sitzung', 'sesión', 29, 'Nomen'),
('der Minister', 'ministro', 29, 'Nomen'),
('das Bundesland', 'estado federado', 29, 'Nomen'),
('der Politiker', 'político', 29, 'Nomen'),
('das Grundgesetz', 'constitución', 29, 'Nomen'),
('das Gericht', 'tribunal', 29, 'Nomen'),
('wählen', 'votar', 29, 'Verb'),
('die Wahl', 'elección', 29, 'Nomen'),
('die Mehrheit', 'mayoría', 29, 'Nomen'),
('mit Mehrheit', 'por mayoría', 29, 'Ausdruck'),
('einheitlich', 'uniforme', 29, 'Adjektiv/Adverb'),
('das Verhältnis', 'proporción', 29, 'Nomen'),
('der Wähler', 'elector', 29, 'Nomen'),
('die Partei', 'partido', 29, 'Nomen'),
('der Stimmzettel', 'papeleta', 29, 'Nomen'),
('die Stimme', 'voto', 29, 'Nomen'),
('ungültig', 'no válido', 29, 'Adjektiv/Adverb'),
('die Hochrechnung', 'estimación', 29, 'Nomen'),
('der Sitz', 'escaño', 29, 'Nomen'),
('koalieren', 'coalición', 29, 'Verb'),
('wahlberechtigt', 'con derecho a voto', 29, 'Adjektiv/Adverb'),
('die Abbildung', 'imagen', 29, 'Nomen'),
('der Zuhörer', 'oyente', 29, 'Nomen'),
('die Änderung', 'cambio', 29, 'Nomen'),
('die Aufmerksamkeit', 'atención', 29, 'Nomen'),
('eine Entscheidung treffen', 'tomar decisión', 29, 'Verb'),
('der Gedanke', 'idea', 29, 'Nomen'),
('sich Gedanken machen über', 'reflexionar', 29, 'Verb'),
('die Anzahl', 'cantidad', 29, 'Nomen'),
('die Gewalt', 'violencia', 29, 'Nomen'),
('die Initiative', 'iniciativa', 29, 'Nomen'),
('die Mischung', 'mezcla', 29, 'Nomen'),
('das Prinzip', 'principio', 29, 'Nomen'),
('die Treue', 'lealtad', 29, 'Nomen')
on conflict (de, es, thema, type) do nothing;
